### ISSUE TITLE
 Generating the data 

### ISSUE THREAD

**Issue by ayano721** [fluidnetsc22/fluidnet_sc22#1]
Hi, 
I tried to generate training data for 3d using manta at Fluid-net repository like your readme,

```
Dataset We use the same 3D dataset as the original FluidNet [Section 1: Generating the data - Generating training data](https://github.com/google/FluidNet#1-generating-the-data) (generated with MantaFlow) for training our CNN.
```

I got return 
```
FluidSolver::solvePressure skipping CorrectVelocity since res is nan!
``` 
a lot.
i think their repository is using their [custom manta fork](https://github.com/kristofe/manta).
So when you generate data, do you set for specific parameter for manta? 

Best,

**Comment by fluidnetsc22** [comment]
Hi,
First of all, thank you for testing the repository and trying to generate the training dataset. So indeed the dataset is generated using the custom manta fork.  The dataset it's generated exactly with the mantaflow fork as indicated in the Tompson's repository:

BUILDING MANTAFLOW

The first step is to download the [custom manta fork](https://github.com/kristofe/manta).

`cd FluidNet/`
`git clone git@github.com:kristofe/manta.git`

Next, you must build mantaflow using the cmake system.


I just wanted to make sure that none of the data generation is original work, we directly took Tompson's dataset (while the training, testing and simulating module, despite being strongly influenced on Tompson's fluidnet and mantaflow is indeed part of this work).

Concerning the nan residual, using the preconditioner for this case with mantaflow tends to sometimes be unstable. However, in the [training dataset generation](https://github.com/kristofe/manta/blob/master/scenes/_trainingData.py) in line 287, if the residual is a nan they solve the pressure equation without preconditioning, which tends to solve the issue. Moreover, even for cases where not using the preconditioner is not enough, the divergent velocity fields are discarded and a new simulation is started to avoid potential issues. This condition, despite being a hack, it's supposed to be enough for successfully generating the dataset.

Moreover,  it should be highlighted that in the trainings tested in this work only a physical loss is used, so the pressure field issued from mantaflow is not completely necessary to perform any trainings, as long as the input divergence fields are coherent.  

So personally, no specific parameters apart from those described by Tompson were used. 

I hope that my response was useful, anb happy to answer further questions,

Thanks in advance,

**Comment by ayano721** [comment]
Thank you so much for your helpful reply.
I tried with the same setting as you say (same as the original repo), and I will check the results with these training data.

Thank you so much!!
